# Q1

details

In [2]:
import os.path
import pandas as pd
import numpy as np
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
if not os.path.exists( "AutoMpg_question1.csv" ):
    print("Missing dataset file - AutoMpg_question1.csv")

In [3]:
df_full = pd.read_csv( "AutoMpg_question1.csv" )

Now lets check all the countries that have data

In [4]:
df_full["horsepower"].unique()

array([130., 165., 150., 140., 198., 220., 215., 225., 190., 170., 160.,
        95.,  nan,  85.,  88.,  46.,  87.,  90., 113., 200., 210., 193.,
       100., 105., 175., 153., 180.,  72.,  86.,  70.,  76.,  65.,  69.,
        60.,  80.,  54., 208., 155.,  97., 112.,  92., 145., 137., 158.,
       167.,  94., 107., 230.,  49.,  75.,  91., 110., 122.,  67.,  83.,
        78.,  52.,  61.,  93., 148., 129.,  96.,  71.,  98., 115.,  53.,
        81.,  79., 152., 102., 108., 120.,  68.,  58., 149.,  89.,  63.,
        48.,  66., 139., 103., 125., 133., 138., 135., 142.,  77.,  62.,
       132.,  84.,  64.,  74., 116.,  82.])

In [10]:
df_full.head(5)

,horsepower,mpg,cylinders,displacement,weight,acceleration,model year,origin,car name
0,130.0,18.0,8.0,307.0,3504.0,12.0,70.0,1.0,chevrolet chevelle malibu
1,165.0,15.0,8.0,350.0,3693.0,11.5,70.0,1.0,buick skylark 320
2,150.0,18.0,8.0,318.0,3436.0,11.0,70.0,1.0,plymouth satellite
3,150.0,16.0,8.0,304.0,3433.0,12.0,70.0,1.0,amc rebel sst
4,140.0,17.0,8.0,302.0,3449.0,10.5,70.0,1.0,ford torino

In [11]:
horsepower_avg = df_full["horsepower"].mean()

In [14]:
df_full["horsepower"] = df_full["horsepower"].fillna(horsepower_avg)

In [15]:
df_full["horsepower"]

0      130.000000
1      165.000000
2      150.000000
3      150.000000
4      140.000000
5      198.000000
6      220.000000
7      215.000000
8      225.000000
9      190.000000
10     170.000000
11     160.000000
12     150.000000
13     225.000000
14      95.000000
15      95.000000
16     104.267016
17      85.000000
18      88.000000
19      46.000000
20      87.000000
21      90.000000
22      95.000000
23     113.000000
24      90.000000
25     215.000000
26     200.000000
27     210.000000
28     193.000000
29      88.000000
          ...
368     88.000000
369     88.000000
370     85.000000
371     84.000000
372     90.000000
373     92.000000
374    104.267016
375     74.000000
376     68.000000
377     68.000000
378     63.000000
379     70.000000
380     88.000000
381     75.000000
382     70.000000
383     67.000000
384     67.000000
385     67.000000
386    110.000000
387     85.000000
388     92.000000
389    112.000000
390     96.000000
391     84.000000
392     90.000000
393     86.000000
394     52.000000
395     84.000000
396     79.000000
397     82.000000
Name: horsepower, Length: 398, dtype: float64

Question 1.2

In [16]:
df_full["origin"]

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
5      1.0
6      1.0
7      1.0
8      1.0
9      NaN
10     1.0
11     1.0
12     1.0
13     1.0
14     3.0
15     1.0
16     1.0
17     1.0
18     3.0
19     2.0
20     2.0
21     2.0
22     2.0
23     2.0
24     1.0
25     1.0
26     1.0
27     1.0
28     NaN
29     3.0
      ...
368    1.0
369    1.0
370    1.0
371    1.0
372    1.0
373    1.0
374    1.0
375    2.0
376    3.0
377    3.0
378    1.0
379    1.0
380    3.0
381    3.0
382    3.0
383    3.0
384    3.0
385    3.0
386    1.0
387    1.0
388    1.0
389    1.0
390    3.0
391    1.0
392    1.0
393    1.0
394    2.0
395    1.0
396    1.0
397    1.0
Name: origin, Length: 398, dtype: float64

In [19]:
origin_min = df_full["origin"].min()
df_full["origin"] = df_full["origin"].fillna(origin_min)
df_full["origin"]

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
5      1.0
6      1.0
7      1.0
8      1.0
9      1.0
10     1.0
11     1.0
12     1.0
13     1.0
14     3.0
15     1.0
16     1.0
17     1.0
18     3.0
19     2.0
20     2.0
21     2.0
22     2.0
23     2.0
24     1.0
25     1.0
26     1.0
27     1.0
28     1.0
29     3.0
      ...
368    1.0
369    1.0
370    1.0
371    1.0
372    1.0
373    1.0
374    1.0
375    2.0
376    3.0
377    3.0
378    1.0
379    1.0
380    3.0
381    3.0
382    3.0
383    3.0
384    3.0
385    3.0
386    1.0
387    1.0
388    1.0
389    1.0
390    3.0
391    1.0
392    1.0
393    1.0
394    2.0
395    1.0
396    1.0
397    1.0
Name: origin, Length: 398, dtype: float64

In [23]:
df_full.to_csv(r'question1 out.csv')

In [3]:
if not os.path.exists( "AutoMpg_question2_b.csv" ):
    print("Missing dataset file - AutoMpg_question2_b.csv")

df_2b = pd.read_csv( "AutoMpg_question2_b.csv" )

In [7]:
df_2b.head(5)

,horsepower,origin,mpg,cylinders,displacement,weight,acceleration,model year,car name,other
0,130,1,18.0,8,307.0,3504,12.0,70,chevrolet chevelle malibu,2
1,165,1,15.0,8,350.0,3693,11.5,70,buick skylark 320,2
2,150,1,18.0,8,318.0,3436,11.0,70,plymouth satellite,2
3,150,1,16.0,8,304.0,3433,12.0,70,amc rebel sst,2
4,140,1,17.0,8,302.0,3449,10.5,70,ford torino,2

In [6]:
df_2b.rename(columns={'name': 'car name'}, inplace=True)

In [8]:
if not os.path.exists( "AutoMpg_question2_a.csv" ):
    print("Missing dataset file - AutoMpg_question2_a.csv")

df_2a = pd.read_csv( "AutoMpg_question2_a.csv" )

In [9]:
df_2a.head(5)

,horsepower,origin,mpg,cylinders,displacement,weight,acceleration,model year,car name
0,130,1.0,18.0,8.0,307.0,3504.0,12.0,70.0,chevrolet chevelle malibu
1,165,1.0,15.0,8.0,350.0,3693.0,11.5,70.0,buick skylark 320
2,150,1.0,18.0,8.0,318.0,3436.0,11.0,70.0,plymouth satellite
3,150,1.0,16.0,8.0,304.0,3433.0,12.0,70.0,amc rebel sst
4,140,1.0,17.0,8.0,302.0,3449.0,10.5,70.0,ford torino

In [11]:
other = 1
df_2a["other"] = other

In [12]:
df_2a.head(5)

,horsepower,origin,mpg,cylinders,displacement,weight,acceleration,model year,car name,other
0,130,1.0,18.0,8.0,307.0,3504.0,12.0,70.0,chevrolet chevelle malibu,1
1,165,1.0,15.0,8.0,350.0,3693.0,11.5,70.0,buick skylark 320,1
2,150,1.0,18.0,8.0,318.0,3436.0,11.0,70.0,plymouth satellite,1
3,150,1.0,16.0,8.0,304.0,3433.0,12.0,70.0,amc rebel sst,1
4,140,1.0,17.0,8.0,302.0,3449.0,10.5,70.0,ford torino,1

In [16]:
df_combined = pd.concat([df_2a, df_2b], axis=0)
df_combined.reset_index(drop=True)

,horsepower,origin,mpg,cylinders,displacement,weight,acceleration,model year,car name,other
0,130,1.0,18.0,8.0,307.0,3504.0,12.0,70.0,chevrolet chevelle malibu,1
1,165,1.0,15.0,8.0,350.0,3693.0,11.5,70.0,buick skylark 320,1
2,150,1.0,18.0,8.0,318.0,3436.0,11.0,70.0,plymouth satellite,1
3,150,1.0,16.0,8.0,304.0,3433.0,12.0,70.0,amc rebel sst,1
4,140,1.0,17.0,8.0,302.0,3449.0,10.5,70.0,ford torino,1
5,198,1.0,15.0,8.0,429.0,4341.0,10.0,70.0,ford galaxie 500,1
6,220,1.0,14.0,8.0,454.0,4354.0,9.0,70.0,chevrolet impala,1
7,215,1.0,14.0,8.0,440.0,4312.0,8.5,70.0,plymouth fury iii,1
8,225,1.0,14.0,8.0,455.0,4425.0,10.0,70.0,pontiac catalina,1
9,190,1.0,15.0,8.0,390.0,3850.0,8.5,70.0,amc ambassador dpl,1
10,170,1.0,15.0,8.0,383.0,3563.0,10.0,70.0,dodge challenger se,1
11,160,1.0,14.0,8.0,340.0,3609.0,8.0,70.0,plymouth 'cuda 340,1
12,150,1.0,15.0,8.0,400.0,3761.0,9.5,70.0,chevrolet monte carlo,1
13,225,1.0,14.0,8.0,455.0,3086.0,10.0,70.0,buick estate wagon (sw),1
14,95,3.0,24.0,4.0,113.0,2372.0,15.0,70.0,toyota corona mark ii,1
15,95,1.0,22.0,6.0,198.0,2833.0,15.5,70.0,plymouth duster,1
16,150,1.0,18.0,6.0,199.0,2774.0,15.5,70.0,amc hornet,1
17,85,1.0,21.0,6.0,200.0,2587.0,16.0,70.0,ford maverick,1
18,88,3.0,27.0,4.0,97.0,2130.0,14.5,70.0,datsun pl510,1
19,46,2.0,26.0,4.0,97.0,1835.0,20.5,70.0,volkswagen 1131 deluxe sedan,1
20,87,2.0,25.0,4.0,110.0,2672.0,17.5,70.0,peugeot 504,1
21,90,2.0,24.0,4.0,107.0,2430.0,14.5,70.0,audi 100 ls,1
22,95,2.0,25.0,4.0,104.0,2375.0,17.5,70.0,saab 99e,1
23,113,2.0,26.0,4.0,121.0,2234.0,12.5,70.0,bmw 2002,1
24,90,1.0,21.0,6.0,199.0,2648.0,15.0,70.0,amc gremlin,1
25,215,1.0,10.0,8.0,360.0,4615.0,14.0,70.0,ford f250,1
26,200,1.0,10.0,8.0,307.0,4376.0,15.0,70.0,chevy c20,1
27,210,1.0,11.0,8.0,318.0,4382.0,13.5,70.0,dodge d200,1
28,193,1.0,9.0,8.0,304.0,4732.0,18.5,70.0,hi 1200d,1
29,88,3.0,27.0,4.0,97.0,2130.0,14.5,71.0,datsun pl510,1
...,...,...,...,...,...,...,...,...,...,...
766,88,1.0,27.0,4.0,112.0,2640.0,18.6,82.0,chevrolet cavalier wagon,2
767,88,1.0,34.0,4.0,112.0,2395.0,18.0,82.0,chevrolet cavalier 2-door,2
768,85,1.0,31.0,4.0,112.0,2575.0,16.2,82.0,pontiac j2000 se hatchback,2
769,84,1.0,29.0,4.0,135.0,2525.0,16.0,82.0,dodge aries se,2
770,90,1.0,27.0,4.0,151.0,2735.0,18.0,82.0,pontiac phoenix,2
771,92,1.0,24.0,4.0,140.0,2865.0,16.4,82.0,ford fairmont futura,2
772,150,1.0,23.0,4.0,151.0,3035.0,20.5,82.0,amc concord dl,2
773,74,2.0,36.0,4.0,105.0,1980.0,15.3,82.0,volkswagen rabbit l,2
774,68,3.0,37.0,4.0,91.0,2025.0,18.2,82.0,mazda glc custom l,2
775,68,3.0,31.0,4.0,91.0,1970.0,17.6,82.0,mazda glc custom,2
776,63,1.0,38.0,4.0,105.0,2125.0,14.7,82.0,plymouth horizon miser,2
777,70,1.0,36.0,4.0,98.0,2125.0,17.3,82.0,mercury lynx l,2
778,88,3.0,36.0,4.0,120.0,2160.0,14.5,82.0,nissan stanza xe,2
779,75,3.0,36.0,4.0,107.0,2205.0,14.5,82.0,honda accord,2
780,70,3.0,34.0,4.0,108.0,2245.0,16.9,82.0,toyota corolla,2
781,67,3.0,38.0,4.0,91.0,1965.0,15.0,82.0,honda civic,2
782,67,3.0,32.0,4.0,91.0,1965.0,15.7,82.0,honda civic (auto),2
783,67,3.0,38.0,4.0,91.0,1995.0,16.2,82.0,datsun 310 gx,2
784,110,1.0,25.0,6.0,181.0,2945.0,16.4,82.0,buick century limited,2
785,85,1.0,38.0,6.0,262.0,3015.0,17.0,82.0,oldsmobile cutlass ciera (diesel),2
786,92,1.0,26.0,4.0,156.0,2585.0,14.5,82.0,chrysler lebaron medallion,2
787,112,1.0,22.0,6.0,232.0,2835.0,14.7,82.0,ford granada l,2
788,96,3.0,32.0,4.0,144.0,2665.0,13.9,82.0,toyota celica gt,2
789,84,1.0,36.0,4.0,135.0,2370.0,13.0,82.0,dodge charger 2.2,2
790,90,1.0,27.0,4.0,151.0,2950.0,17.3,82.0,chevrolet camaro,2
791,86,1.0,27.0,4.0,140.0,2790.0,15.6,82.0,ford mustang gl,2
792,52,2.0,44.0,4.0,97.0,2130.0,24.6,82.0,vw pickup,2
793,84,1.0,32.0,4.0,135.0,2295.0,11.6,82.0,dodge rampage,2
794,79,1.0,28.0,4.0,120.0,2625.0,18.6,82.0,ford ranger,2
795,82,1.0,31.0,4.0,119.0,2720.0,19.4,82.0,chevy s-10,2

In [17]:
df_combined

,horsepower,origin,mpg,cylinders,displacement,weight,acceleration,model year,car name,other
0,130,1.0,18.0,8.0,307.0,3504.0,12.0,70.0,chevrolet chevelle malibu,1
1,165,1.0,15.0,8.0,350.0,3693.0,11.5,70.0,buick skylark 320,1
2,150,1.0,18.0,8.0,318.0,3436.0,11.0,70.0,plymouth satellite,1
3,150,1.0,16.0,8.0,304.0,3433.0,12.0,70.0,amc rebel sst,1
4,140,1.0,17.0,8.0,302.0,3449.0,10.5,70.0,ford torino,1
5,198,1.0,15.0,8.0,429.0,4341.0,10.0,70.0,ford galaxie 500,1
6,220,1.0,14.0,8.0,454.0,4354.0,9.0,70.0,chevrolet impala,1
7,215,1.0,14.0,8.0,440.0,4312.0,8.5,70.0,plymouth fury iii,1
8,225,1.0,14.0,8.0,455.0,4425.0,10.0,70.0,pontiac catalina,1
9,190,1.0,15.0,8.0,390.0,3850.0,8.5,70.0,amc ambassador dpl,1
10,170,1.0,15.0,8.0,383.0,3563.0,10.0,70.0,dodge challenger se,1
11,160,1.0,14.0,8.0,340.0,3609.0,8.0,70.0,plymouth 'cuda 340,1
12,150,1.0,15.0,8.0,400.0,3761.0,9.5,70.0,chevrolet monte carlo,1
13,225,1.0,14.0,8.0,455.0,3086.0,10.0,70.0,buick estate wagon (sw),1
14,95,3.0,24.0,4.0,113.0,2372.0,15.0,70.0,toyota corona mark ii,1
15,95,1.0,22.0,6.0,198.0,2833.0,15.5,70.0,plymouth duster,1
16,150,1.0,18.0,6.0,199.0,2774.0,15.5,70.0,amc hornet,1
17,85,1.0,21.0,6.0,200.0,2587.0,16.0,70.0,ford maverick,1
18,88,3.0,27.0,4.0,97.0,2130.0,14.5,70.0,datsun pl510,1
19,46,2.0,26.0,4.0,97.0,1835.0,20.5,70.0,volkswagen 1131 deluxe sedan,1
20,87,2.0,25.0,4.0,110.0,2672.0,17.5,70.0,peugeot 504,1
21,90,2.0,24.0,4.0,107.0,2430.0,14.5,70.0,audi 100 ls,1
22,95,2.0,25.0,4.0,104.0,2375.0,17.5,70.0,saab 99e,1
23,113,2.0,26.0,4.0,121.0,2234.0,12.5,70.0,bmw 2002,1
24,90,1.0,21.0,6.0,199.0,2648.0,15.0,70.0,amc gremlin,1
25,215,1.0,10.0,8.0,360.0,4615.0,14.0,70.0,ford f250,1
26,200,1.0,10.0,8.0,307.0,4376.0,15.0,70.0,chevy c20,1
27,210,1.0,11.0,8.0,318.0,4382.0,13.5,70.0,dodge d200,1
28,193,1.0,9.0,8.0,304.0,4732.0,18.5,70.0,hi 1200d,1
29,88,3.0,27.0,4.0,97.0,2130.0,14.5,71.0,datsun pl510,1
...,...,...,...,...,...,...,...,...,...,...
368,88,1.0,27.0,4.0,112.0,2640.0,18.6,82.0,chevrolet cavalier wagon,2
369,88,1.0,34.0,4.0,112.0,2395.0,18.0,82.0,chevrolet cavalier 2-door,2
370,85,1.0,31.0,4.0,112.0,2575.0,16.2,82.0,pontiac j2000 se hatchback,2
371,84,1.0,29.0,4.0,135.0,2525.0,16.0,82.0,dodge aries se,2
372,90,1.0,27.0,4.0,151.0,2735.0,18.0,82.0,pontiac phoenix,2
373,92,1.0,24.0,4.0,140.0,2865.0,16.4,82.0,ford fairmont futura,2
374,150,1.0,23.0,4.0,151.0,3035.0,20.5,82.0,amc concord dl,2
375,74,2.0,36.0,4.0,105.0,1980.0,15.3,82.0,volkswagen rabbit l,2
376,68,3.0,37.0,4.0,91.0,2025.0,18.2,82.0,mazda glc custom l,2
377,68,3.0,31.0,4.0,91.0,1970.0,17.6,82.0,mazda glc custom,2
378,63,1.0,38.0,4.0,105.0,2125.0,14.7,82.0,plymouth horizon miser,2
379,70,1.0,36.0,4.0,98.0,2125.0,17.3,82.0,mercury lynx l,2
380,88,3.0,36.0,4.0,120.0,2160.0,14.5,82.0,nissan stanza xe,2
381,75,3.0,36.0,4.0,107.0,2205.0,14.5,82.0,honda accord,2
382,70,3.0,34.0,4.0,108.0,2245.0,16.9,82.0,toyota corolla,2
383,67,3.0,38.0,4.0,91.0,1965.0,15.0,82.0,honda civic,2
384,67,3.0,32.0,4.0,91.0,1965.0,15.7,82.0,honda civic (auto),2
385,67,3.0,38.0,4.0,91.0,1995.0,16.2,82.0,datsun 310 gx,2
386,110,1.0,25.0,6.0,181.0,2945.0,16.4,82.0,buick century limited,2
387,85,1.0,38.0,6.0,262.0,3015.0,17.0,82.0,oldsmobile cutlass ciera (diesel),2
388,92,1.0,26.0,4.0,156.0,2585.0,14.5,82.0,chrysler lebaron medallion,2
389,112,1.0,22.0,6.0,232.0,2835.0,14.7,82.0,ford granada l,2
390,96,3.0,32.0,4.0,144.0,2665.0,13.9,82.0,toyota celica gt,2
391,84,1.0,36.0,4.0,135.0,2370.0,13.0,82.0,dodge charger 2.2,2
392,90,1.0,27.0,4.0,151.0,2950.0,17.3,82.0,chevrolet camaro,2
393,86,1.0,27.0,4.0,140.0,2790.0,15.6,82.0,ford mustang gl,2
394,52,2.0,44.0,4.0,97.0,2130.0,24.6,82.0,vw pickup,2
395,84,1.0,32.0,4.0,135.0,2295.0,11.6,82.0,dodge rampage,2
396,79,1.0,28.0,4.0,120.0,2625.0,18.6,82.0,ford ranger,2
397,82,1.0,31.0,4.0,119.0,2720.0,19.4,82.0,chevy s-10,2

In [19]:
df_combined.to_csv(r'question2_out.csv')